### ISSUE TITLE
RPCError (RPCError: got code 19 with msg "Unable to perform request".)

### ISSUE THREAD

**Issue by kinggongzilla** [WalletConnect/Web3ModalFlutter#118]
After connecting with a wallet the web3modal package throws the error:

`RPCError (RPCError: got code 19 with msg "Unable to perform request".)`

`function: "eth_getBalance"`

multiple times.

The error is coming from the catch statement in `makeRPCCall()`

**Comment by quetool** [comment]
Hello @kinggongzilla, checking if you still need help here. That error looks like a direct error from web3dart package and it's most probably due to the wallet you are connecting to not supporting that method. On our side you should read `WalletConnectError(code: 5101, message: Unsupported methods. The method eth_getBalance is not supported, data: null)`

**Comment by kinggongzilla** [comment]
Hi
Sorry for the delay.
Yes I can confirm that `WalletConnectError(code: 5101, message: Unsupported methods. The method eth_getBalance is not supported, data: null)` is the error that is thrown.

Does this error have any impact on functionality apart from  not being able to call eth_getBalance?

Thanks again for your help!

**Comment by quetool** [comment]
Hello @kinggongzilla! No impact whatsoever. Also balance for the selected chain is already embedded on Web3Modal but if this is a requested feature I could include it as a separate method inside W3MService in the near future.

**Comment by quetool** [comment]
Hello @kinggongzilla! I'll close this issue for now as it seems resolved but please do let me know otherwise.
