### ISSUE TITLE
Intialisation take forever in production app

### ISSUE THREAD

**Issue by praveen4030** [WalletConnect/Web3ModalFlutter#138]
**Describe the bug**
Sometimes randomly service.init() takes forever to load and even after restart/reinstalling the app doesn't works.

**Comment by quetool** [comment]
Hello @praveen4030, can you complete the template where possible?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Meaningful logs**
Any error or information log that would help identify the issue

**Reproducible code**
Minimum reproducible code of the issue

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Web3Modal Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by quetool** [comment]
Hello @praveen4030, do you still need help on this?
