### ISSUE TITLE
Event listerners for transaction state

### ISSUE THREAD

**Issue by Mindsetter** [WalletConnect/Web3ModalFlutter#156]
I'm using web3modal_flutter 3.2.2 to interact with my smart contract.  I want to display a message when a user approves or rejects a transaction. I have gone through the documentation but to no avail.

@quetool  How can I set up an event listener for the transaction state?

Thank you

**Comment by quetool** [comment]
Hello @Mindsetter! This is an interesting inquiry. Let me understand, you want to communicate the user when the transaction is validated in the blockchain of just upon successful broadcast?

**Comment by Mindsetter** [comment]
Hello @quetool , Yes I would like to communicate to the user upon successfully broadcast and also when the transaction is validated on the blockchain. If there is any similar way around it you can share it with me. Thank you

**Comment by quetool** [comment]
Well, the result of the transaction being broadcasted is in fact the hash you receive as a result of requesting `eth_sendTransaction`, so there is that. 

Then, regarding the actual confirmations of the transaction you can use our blockchain api https://specs.walletconnect.com/2.0/specs/servers/blockchain/blockchain-rpc-api to call `eth_getTransactionByHash` with the given hash like this: https://ethereum.stackexchange.com/questions/2881/how-to-get-the-transaction-confirmations-using-the-json-rpc

I honestly don't know if there are any websocket libraries to do this in a subscription model but basically once you have the transaction hash you can use whatever you'd like in order to get transaction detail.

**Comment by chris13524** [comment]
There may be other RPC providers that provide a live view off the transaction confirmation state (e.g. eth_getTransactionByHash RPC or otherwise). But with our Blockchain API you can poll for the transaction state every few seconds, but just enable connection reuse for efficiency.
