### ISSUE TITLE
Connect only one type of Wallet

### ISSUE THREAD

**Issue by MrCube72** [WalletConnect/Web3ModalFlutter#57]
I'm trying to enable connect only MetaMask Wallet in my dApp, but the new version of WalletModal doesn't support this option. It seems "includedWalletIds" include not only the selected Wallets (in my case:

```dart
final Set<String> includedWalletIds = {
  'c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96', // MetaMask
};
```
"excludedWalletIds" seems work, but V3 doesn't have the option exclude ALL other Wallets (like in V2:

```dart
recommendedWalletIds: {
      'c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96', // MetaMask
    },
```
    excludedWalletState: ExcludedWalletState.all,
Do you plan any similar options?
Thanks...

**Comment by quetool** [comment]
Hello @MrCube72 , a fix is coming for your first issue, see here -> https://github.com/WalletConnect/Web3ModalFlutter/issues/56

>  but V3 doesn't have the option exclude ALL other Wallets (like in V2:
There is no exclude all options, on V3 either you pass a set of included wallets (that would be the only wallets to show) or you pass a set of excluded wallets to hide them).

I'll close this issue as duplicate, keep an eye on https://github.com/WalletConnect/Web3ModalFlutter/issues/56 but the fix is most likely to be shipped today

**Comment by quetool** [comment]
Hello @MrCube72 ! Issue has been fixed in latest beta

```
dependencies:
  web3modal_flutter: ^3.0.0-beta18
```
