### ISSUE TITLE
_fetchNativeAppData get uri Failed

### ISSUE THREAD

**Issue by nuzhata** [WalletConnect/Web3ModalFlutter#68]
ClientException with SocketException: Failed 
host lookup: 'api.web3modal.com' (OS Error: No address associated with hostname, errno = 7),
 uri=https://api.web3modal.com/getAndroidData

**Comment by nuzhata** [comment]
explorer_service.dart line 164

**Comment by quetool** [comment]
Do you have internet connection, @nuzhata? Because that happens when there's no internet connection. `/getAndroidData` it's also the first query the SDK does so I'm 99,9% you don't have internet connection in your device.

If you do have it, is this happening on iOS? Android? Where? Do you also have `<uses-permission android:name="android.permission.INTERNET"/>` on Android?

It's pretty difficult to assist you with these kind of reports...

**Comment by nuzhata** [comment]
that link is unavailable in our country Ir

**Comment by nuzhata** [comment]
Error 1009 Ray ID: 82dc95f38d5518da • 2023-11-29 17:31:42 UTC
Access denied

**Comment by nuzhata** [comment]
Thanks for your feedback

**Comment by quetool** [comment]
Oh ok, yes, indeed if you are in any OFAC-restricted country you won't be able to query it, see https://walletconnect.com/terms

**Comment by quetool** [comment]
Closing this issue. Re-open if needed. Thanks!
